# Generated by Django 5.0.3 on 2024-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='isDoctor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='isPatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='isDoctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='isManager',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='isPatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='isDoctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='isPatient',
            field=models.BooleanField(default=True),
        ),
    ]
