# Generated by Django 5.0.3 on 2024-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_doctorprofile_isdoctor_doctorprofile_ismanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='bloodGroup',
            field=models.CharField(default='O+', max_length=6),
            preserve_default=False,
        ),
    ]
