# Generated by Django 5.0.3 on 2024-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_patientprofile_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='fName',
            field=models.CharField(default='asd', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='lName',
            field=models.CharField(default='asddas', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='fName',
            field=models.CharField(default='asasas', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='lName',
            field=models.CharField(default='adasda', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='fName',
            field=models.CharField(default='asdasdasd', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lName',
            field=models.CharField(default='asdasdasd', max_length=30),
            preserve_default=False,
        ),
    ]
