# Generated by Django 5.0.3 on 2024-03-24 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_doctorprofile_fname_doctorprofile_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=20)),
                ('referal', models.CharField(max_length=30, null=True)),
                ('referredDoctor', models.CharField(max_length=30, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.patientprofile')),
            ],
        ),
    ]
