# Generated by Django 5.0.3 on 2024-03-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_slots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
