# Generated by Django 5.0.3 on 2024-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_slots_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='doctor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='referal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='referredDoctor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
