# Generated by Django 5.0.3 on 2024-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_slot_doctor_alter_slot_referal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='referredDoctor',
            new_name='referredFrom',
        ),
        migrations.AlterField(
            model_name='slot',
            name='referal',
            field=models.BooleanField(default=False),
        ),
    ]
