# Generated by Django 4.0 on 2024-05-02 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_doctorprofile_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.doctorprofile'),
        ),
    ]
